name: ble_chess_peripheral_driver
description: A Chessboard Driver written in pure Dart
version: 0.0.10
repository: https://github.com/dkwach/chess_peripheral_driver

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.3.0
  ble_backend: ^1.3.0