name: universal_chess_driver
description: A Chessboard Driver written in pure Dart
version: 0.0.10
repository: https://github.com/dkwach/BleChessDriver

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
